name: opencode-review

on:
  schedule:
    - cron: "0 9 * * 1" # Every Monday at 9am UTC

jobs:
  review:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
      pull-requests: write
      issues: read
    steps:
      - uses: actions/checkout@v6
        with:
          persist-credentials: true
          token: ${{ secrets.GITHUB_TOKEN }}  
      - uses: anomalyco/opencode/github@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          model: opencode/nemotron-3-ultra-free
          use_github_token: true
          prompt: |
            Review the codebase and look for:
            - Check for code quality
            - Look for potential bugs
            - Suggest improvements
            - Create a pull requests with the code changes suggested. 
